name: 4. HTML Check
on: push
jobs:
  check-html-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v0.5
      with:
        root: .
        log_level: INFO
